export const ActionTypes = {
    GET_PRODUCTS: " GET_PRODUCTS",
    VIEW_PRODUCT_DETAIL: "  VIEW_PRODUCT_DETAIL",
    REMOVE_SELECTED_PRODUCT: " REMOVE_SELECTED_PRODUCT",
    ADD_CART: "ADD_CART",
    REMOVE_CART: "REMOVE_CART",
};